runmode: debug
addr: :8088
name: apiserver
url: http://127.0.0.1:8088
max_ping_count: 10
log:
  writers: file,stdout
  logger_level: DEBUG
  logger_file: log/ttstore.log
  log_format_text: false
  rollingPolicy: size
  log_rotate_date: 1
  log_rotate_size: 1
  log_backup_count: 7
db:
  addr: 127.0.0.1:3306
  name: tecnotree_store
  username: ttstore
  password: ttstore123456
